package com.casecode.pos.core.printer.model

enum class PrinterStatusCode {
    FINISH_SUCCESS,
    FINISH_NO_PRINTER,
    FINISH_PRINTER_DISCONNECTED,
    FINISH_PARSER_ERROR,
    FINISH_ENCODING_ERROR,
    FINISH_BARCODE_ERROR,
    PROGRESS_CONNECTING,
    PROGRESS_CONNECTED,
    PROGRESS_PRINTING,
    PROGRESS_PRINTED,
}